apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-provider-detector
  labels:
    app: k8s-provider-detector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-provider-detector
  labels:
    app: k8s-provider-detector
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-provider-detector
  labels:
    app: k8s-provider-detector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-provider-detector
subjects:
- kind: ServiceAccount
  name: k8s-provider-detector
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-provider-detector
  name: k8s-provider-detector
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-provider-detector
  template:
    metadata:
      labels:
        app: k8s-provider-detector
      name: k8s-provider-detector
    spec:
      serviceAccountName: k8s-provider-detector
      containers:
      - image: emruzhossain/k8s-provider-detector
        imagePullPolicy: Always
        name: provider-detector
